### ISSUE TITLE
how to configure server's timezone

### ISSUE THREAD

**Issue by jianlins** [MariaDB4j/MariaDB4j#90] opened 2017-10-06 21:20 UTC
Hello,

When I try to connect a running server. I get this error message:

Exception in thread "main" java.sql.SQLException: The server time zone value 'MDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

Is there anyway to configure that on the server side?

Thanks

**Comment by Angrynut** [comment] 2017-10-17 10:03
The following fragment works for me:

**Comment by vorburger** [comment] 2018-01-13 01:46
@Angrynut thanks for having provided support to @jianlins here!

If either of you guys think that this should somehow be "supported" by MariaDB4j out of the box with method on the DBBuilder, then please feel free to send a PR proposing to add this. If not let me know if you are OK to close this issue. If I don't hear from you within 1 month, I'll close it.

PS: Re. the characterEncoding=utf-8&useUnicode=true, that look related to https://github.com/vorburger/MariaDB4j/issues/52 - again any PR contributions around this would certainly be welcome.

**Comment by jianlins** [comment] 2018-05-10 17:10
Thanks. What is PR proposing ?

**Comment by jianlins** [comment] 2018-05-10 18:02
BTW, @Angrynut , is this scala? How to configure it in Java? There is not a class named "DruidDataSource". Is this another dependency?

Thanks

**Comment by Angrynut** [comment] 2018-06-04 12:22
@jianlins groovy

**Comment by shiyardavid** [comment] 2018-09-10 11:43
is there any update on this ticket.
I have the same issue and embedded DB is not running at all so setting server time zone ins connection URL is not working.
I need a solution for Java please

@vorburger  
@xyzwps

**Comment by vorburger** [comment] 2018-09-10 12:03
@shiyardavid you may misunderstand how open source works - this isn't a "ticket" of a system you pay for and therefore can "expect" support on... :smile: This is a community where people help each other out - if they can.

In this case, it seems that the recommendation is to use `serverTimezone=` in the JDBC connection URL.

As this seems to be more of a generic MariaDB4 JDBC driver question, not something specific to MariaDB4j (the embedded database wrapper which this project provides); let me close this issue - I don't see what there is that this project could do better to "solve" this.  If anyone disagrees and wants to contribute to this project with a PR, then we could always re-open this issue.

**Comment by shDaoud** [comment] 2018-09-28 10:18
Hello,

after a little searching and debugging, I fixed this issue ( you can find the fixed branch in the forked repo in my account)
I test it on windows (since this issue appeared on window 10) and it is working. 
Mainly you need to add a time zone when configuring the DB

    ```
  static DBConfigurationBuilder configBuilder;
	
	@BeforeClass
	public static void set() throws ManagedProcessException{

		configBuilder = DBConfigurationBuilder.newBuilder();
		configBuilder.addArg("--default-time-zone=UTC");
		db = DB.newEmbeddedDB(configBuilder.build());
		
		db.start();
	}
```
@vorburger thanks for your emails

happy coding

**Comment by vorburger** [comment] 2018-10-01 09:45
> configBuilder.addArg("--default-time-zone=UTC");

interesting. Perhaps `DBConfigurationBuilder` should have a `setTimeZone(java.util.TimeZone tz)` method? With a default to `UTC` ?

> I fixed this issue (you can find the fixed branch in the forked repo in my account)

contributions to this project via PR for something like above most welcome!

**Comment by shDaoud** [comment] 2018-10-01 19:52
after debugging, I found that the DB has no timezone tables so I added them and you can use any timezone you want (UTC was just an example)

**Comment by shDaoud** [comment] 2018-10-04 06:13
normally if you install mysql from using any installation package, the file/script "mysql_tzinfo_to_sql" will install these tables from different places (like /usr/share/zoneinfo for linux) but since MariaDB4j is a minimum version of mysql, this file is missing. Windows has special case since there is no timezone infos in the system, so I had to copy missing tables to mysql installation folder.

please check:

[mysql_timezone](https://dev.mysql.com/doc/refman/8.0/en/mysql-tzinfo-to-sql.html)
[stackoverflow: mysql_tzinfo_to_sql program ](https://stackoverflow.com/questions/713319/mysql-mysql-tzinfo-to-sql-program)

**Comment by vorburger** [comment] 2018-10-04 11:36
Interesting. Pull Requests which improve this situation are most welcome...

**Comment by vorburger** [comment] 2018-10-30 17:21
Does anyone want to pick up and finish https://github.com/vorburger/MariaDB4j/pull/177 re. this?

**Comment by rage-shadowman** [comment] 2019-03-13 19:13
> > configBuilder.addArg("--default-time-zone=UTC");

I had to use `.addArg("--default-time-zone=+0:00")` as it wouldn't recognize "GMT" or "UTC" as valid timezones either.

> interesting. Perhaps `DBConfigurationBuilder` should have a `setTimeZone(java.util.TimeZone tz)` method? With a default to `UTC` ?

Yes, please. :)

**Comment by vorburger** [comment] 2019-03-14 10:54
> Perhaps DBConfigurationBuilder should have a setTimeZone(java.util.TimeZone tz) method? With a default to UTC ?
> Yes, please. :)

Pull Requests for this are very welcome... :smile:

**Comment by EasyG0ing1** [comment] 2020-05-15 13:13
NONE of the above worked for me, although I did build the SQL command file using the **mysql_tzinfo_to_sql** command by doing this:

```/usr/local/mysql-8.0.18-macos10.14-x86_64/bin/mysql_tzinfo_to_sql /usr/share/zoneinfo  > ~/JavaApps/time.sql```

I just happen to have mysql 8 installed so I had the program there and it makes a nice file ... the problem is, it doesn't specify which schema the commands should be executed on so not being sure about that, I continued looking into this and found the solution that did work for me. I used Java's timezone in the connection string like so ...  (I intentionally expanded everything out so that it's all broken down nice and simple like ... I don't typically code like this :-)


```
public class db {

public static Connection conn;
private static DB        db;
private static String    workingFolder         = "/Users/michael/JavaApps/EmbeddedMySQL";
private static String    jdbcURL               = "jdbc:mysql://";
private static String    host                  = "localhost";
private static int       port                  = 3306;
private static String    schema                = "MyDatabase";
private static String    ANNOYING_TIMEZONE_FIX = "?serverTimezone=" + TimeZone.getDefault().getID();
private static String    user                  = "root";
private static String    password              = "";
private static String    slash                 = "/";
private static String    colon                 = ":";
private static String    connString            = jdbcURL + host + colon + port + slash + schema + ANNOYING_TIMEZONE_FIX;

public static void setConnection () {
try {
	DBConfigurationBuilder configBuilder = DBConfigurationBuilder.newBuilder().setPort(port).setDataDir(workingFolder);
	db = DB.newEmbeddedDB(configBuilder.build());
	db.start();
	conn =  DriverManager.getConnection(connString, user, password);
    }
    catch (ManagedProcessException | SQLException e) {e.printStackTrace();}
}

}
```

connString ends up looking like this in my time zone (your timezone might be different): 

```jdbc:mysql://localhost:3306/MyOTP?serverTimezone=America/Los_Angeles```

**Comment by vorburger** [comment] 2023-09-19 00:02
Closing ancient issue which hasn't seen any community engagement in a year; any future readers, please open a new issue, or (better) a PR with a fix!

**Closed by vorburger** 2023-09-19 00:02 UTC
Labels: low, helpwanted
