### ISSUE TITLE
Before 3.0.1 release, mysql_install_db.exe: unknown variable 'tmpdir=C:\Users\Administrator\AppData\Local\Temp\MariaDB4j\tmp\54772

### ISSUE THREAD

**Issue by hxing-Do** [MariaDB4j/MariaDB4j#749] opened 2023-06-12 12:15 UTC
ch.vorburger.exec.ManagedProcessException: An error occurred while installing the database

	at ch.vorburger.mariadb4j.DB.install(DB.java:141)
	at ch.vorburger.mariadb4j.DB.newEmbeddedDB(DB.java:89)
	at ch.vorburger.mariadb4j.tests.DBConfigurationBuilderTest.defaultCharacterSet(DBConfigurationBuilderTest.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: ch.vorburger.exec.ManagedProcessException: Program [C:\Users\ADMINI~1\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, --datadir=C:\Users\Administrator\AppData\Local\Temp\MariaDB4j\data\54772, --tmpdir=C:\Users\Administrator\AppData\Local\Temp\MariaDB4j\tmp\54772] (in working directory C:\Users\ADMINI~1\AppData\Local\Temp\MariaDB4j\base) failed, exitValue=7, last 100 lines of console:
C:\Users\ADMINI~1\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe: unknown variable 'tmpdir=C:\Users\Administrator\AppData\Local\Temp\MariaDB4j\tmp\54772'
	at ch.vorburger.exec.ManagedProcess.checkResult(ManagedProcess.java:310)
	at ch.vorburger.exec.ManagedProcess.waitForExitMaxMsWithoutLog(ManagedProcess.java:448)
	at ch.vorburger.exec.ManagedProcess.waitForExit(ManagedProcess.java:416)
	at ch.vorburger.mariadb4j.DB.install(DB.java:139)
	... 27 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 7 (Exit value: 7)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vorburger** [comment] 2023-06-16 19:58
@hxing-Do the root cause appears to be `mysql_install_db.exe: unknown variable 'tmpdir=C:\Users\Administrator\AppData\Local\Temp\MariaDB4j\tmp\54772`? 

Unfortunately I have no idea what could be causing this on your Windows. This definitely works on Linux and Mac OS and Windows, see [this CI build on Windows](https://github.com/MariaDB4j/MariaDB4j/actions/runs/4971648940/jobs/8896318246). It must be something particular on your Windows.

Perhaps other Windows users of this library have an idea.

**Comment by MonsieurBon** [comment] 2023-06-22 13:03
@vorburger I have the same problem on my machine, starting from version 2.5.0. In the CI build you mention, the parameter tmpdir is not passed to install_mysql_db.exe. If I compare 2.4.0 to 2.5.0 I cannot find any change which might add a 'tmpdir' parameter when calling install_mysql_db.exe. Any idea what is happening here?

**Comment by vorburger** [comment] 2023-06-22 15:35
Yes, this is fixed in the current latest 3.0.1 release!

Can you (both) upgrade do that we can close this issue?

**Comment by skarpushin** [comment] 2023-06-30 09:52
@vorburger thank you for providing the fix (I'm facing same issue). But I cannot upgrade to Java 17, I have to stay with Java 11 for now. Would you be so kind to release fix for 2.6.x version?

**Comment by vorburger** [comment] 2023-09-18 23:42
>  cannot upgrade to Java 17, I have to stay with Java 11 for now. Would you be so kind to release fix for 2.6.x version?

@skarpushin as per #717, unfortunately I am unable to sink more time into this side project not for free.

**Closed by vorburger** 2023-09-18 23:42 UTC
Labels: helpwanted, Windows

**Comment by TheKnowles** [comment] 2023-09-19 19:40
> @vorburger thank you for providing the fix (I'm facing same issue). But I cannot upgrade to Java 17, I have to stay with Java 11 for now. Would you be so kind to release fix for 2.6.x version?

@skarpushin this has been fixed with 2.7.2 release: https://github.com/TheKnowles/MariaDB4j/releases/tag/mariaDB4j-2.7.2
